---
title: "Economic Indicators"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(xlsx)
library(ggplot2)


dtGDP <- read.xlsx('fredgraph.xls',sheetName = 'GDP')
dtOtherIndicators <- read.xlsx('fredgraph.xls',sheetName = 'Sheet2')


```


Column {data-width=650}
-----------------------------------------------------------------------

### GDP Quarterly Percent Changed - Seasonaly Adjusted

```{r fig.width=10}

ggplot(dtGDP,aes(x=Date,y=RGDP)) +
  geom_line(color="blue") +
  ggtitle("") +
  xlab("") +
  ylab("") +
  theme(axis.text.x =element_text(size=12),axis.text.y =element_text(size=12))


```

### Civilian Unemployment Rate, Percent, Monthly, Seasonally Adjusted

```{r fig.width=10}

ggplot(dtOtherIndicators,aes(x=Date,y=UNRATE)) +
  geom_line(color="blue") +
  ggtitle("") +
  xlab("") +
  ylab("") +
  theme(axis.text.x =element_text(size=12), axis.text.y =element_text(size=12))


```


Column {data-width=350}
-----------------------------------------------------------------------

### ISM Manufacturing: PMI Composite Index

```{r fig.width=5, fig.height=5}

ggplot(dtOtherIndicators,aes(x=Date,y=ISM.PMI)) +
  geom_line(color="blue") +
  ggtitle("") +
  xlab("") +
  ylab("") +
  theme(axis.text.x =element_text(size=12),axis.text.y =element_text(size=12))

```

### Insight

Average Unemployment Rate from `r min(dtOtherIndicators$Date)` to `r max(dtOtherIndicators$Date)` is `r mean(dtOtherIndicators$UNRATE)`.


